"""empty message

Revision ID: 7e6468b31a62
Revises: ccdf124ca00c
Create Date: 2024-03-30 06:49:55.307139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e6468b31a62'
down_revision = 'ccdf124ca00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('procedure', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('transaction_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['core.users._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes', schema='core')
    op.drop_table('users', schema='core')
    # ### end Alembic commands ###
