"""empty message

Revision ID: b5ce428ecedf
Revises: bdde6fd6108c
Create Date: 2024-03-30 05:25:56.069916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ce428ecedf'
down_revision = 'bdde6fd6108c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # update enum gender_type
    op.execute("ALTER TYPE public.gender_type RENAME TO old_gender_type")
    op.execute("CREATE TYPE public.gender_type AS ENUM ('m', 'f', 'a', 'o')")
    op.execute("ALTER TABLE core.users ALTER COLUMN gender TYPE public.gender_type USING gender::text::public.gender_type")
    op.execute("DROP TYPE old_gender_type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='core')
    # ### end Alembic commands ###
